export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const GET_POSTDATA_REQUEST="GET_POSTDATA_REQUEST"
export const GET_POSTDATA_SUCCESS="GET_POSTDATA_SUCCESS"
export const GET_POSTDATA_FAILURE="GET_POSTDATA_FAILURE"

export const POST_DATA_REQUEST="POST_DATA_REQUEST"
export const POST_DATA_SUCCESS="POST_DATA_SUCCESS"
export const POST_DATA_FAILURE="POST_DATA_FAILURE"

export const POST_LIKES_REQUEST="POST_LIKES_REQUEST"
export const POST_LIKES_SUCCESS="POST_LIKES_SUCCESS"
export const POST_LIKES_FAILURE="POST_LIKES_FAILURE"

export const POST_COMMENTS_REQUEST="POST_COMMENTS_REQUEST"
export const POST_COMMENTS_SUCCESS="POST_COMMENTS_SUCCESS"
export const POST_COMMENTS_FAILURE="POST_COMMENTS_FAILURE"

